/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ShopImport } from './routes/shop'
import { Route as MusicImport } from './routes/music'
import { Route as CheckoutImport } from './routes/checkout'
import { Route as AuthImport } from './routes/auth'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ProductIdImport } from './routes/product.$id'
import { Route as AdminTransactionsImport } from './routes/admin/transactions'
import { Route as AdminProductsImport } from './routes/admin/products'
import { Route as AdminAddProductImport } from './routes/admin/add-product'

// Create/Update Routes

const ShopRoute = ShopImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRoute,
} as any)

const MusicRoute = MusicImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutRoute = CheckoutImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRoute,
} as any)

const ProductIdRoute = ProductIdImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRoute,
} as any)

const AdminTransactionsRoute = AdminTransactionsImport.update({
  id: '/admin/transactions',
  path: '/admin/transactions',
  getParentRoute: () => rootRoute,
} as any)

const AdminProductsRoute = AdminProductsImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRoute,
} as any)

const AdminAddProductRoute = AdminAddProductImport.update({
  id: '/admin/add-product',
  path: '/admin/add-product',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutImport
      parentRoute: typeof rootRoute
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicImport
      parentRoute: typeof rootRoute
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopImport
      parentRoute: typeof rootRoute
    }
    '/admin/add-product': {
      id: '/admin/add-product'
      path: '/admin/add-product'
      fullPath: '/admin/add-product'
      preLoaderRoute: typeof AdminAddProductImport
      parentRoute: typeof rootRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsImport
      parentRoute: typeof rootRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/admin/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsImport
      parentRoute: typeof rootRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/music': typeof MusicRoute
  '/shop': typeof ShopRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/music': typeof MusicRoute
  '/shop': typeof ShopRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/music': typeof MusicRoute
  '/shop': typeof ShopRoute
  '/admin/add-product': typeof AdminAddProductRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout'
    | '/music'
    | '/shop'
    | '/admin/add-product'
    | '/admin/products'
    | '/admin/transactions'
    | '/product/$id'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/checkout'
    | '/music'
    | '/shop'
    | '/admin/add-product'
    | '/admin/products'
    | '/admin/transactions'
    | '/product/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/checkout'
    | '/music'
    | '/shop'
    | '/admin/add-product'
    | '/admin/products'
    | '/admin/transactions'
    | '/product/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  MusicRoute: typeof MusicRoute
  ShopRoute: typeof ShopRoute
  AdminAddProductRoute: typeof AdminAddProductRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  ProductIdRoute: typeof ProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  MusicRoute: MusicRoute,
  ShopRoute: ShopRoute,
  AdminAddProductRoute: AdminAddProductRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  ProductIdRoute: ProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/auth",
        "/checkout",
        "/music",
        "/shop",
        "/admin/add-product",
        "/admin/products",
        "/admin/transactions",
        "/product/$id",
        "/admin/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/checkout": {
      "filePath": "checkout.tsx"
    },
    "/music": {
      "filePath": "music.tsx"
    },
    "/shop": {
      "filePath": "shop.tsx"
    },
    "/admin/add-product": {
      "filePath": "admin/add-product.tsx"
    },
    "/admin/products": {
      "filePath": "admin/products.tsx"
    },
    "/admin/transactions": {
      "filePath": "admin/transactions.tsx"
    },
    "/product/$id": {
      "filePath": "product.$id.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
